### ISSUE TITLE
打印还是有问题。4.0.3版本

### ISSUE THREAD

**Issue by ls960972314** [guowenfh/geek-time-topdf#22]
找到8节课程                                                                      打印出错 Error: ENOENT: no such file or directory, open 'D:\js_code\性能工程高手 课\0-开篇词 \| 代码不要眼前的苟且，而要效率的提升和性能的优化.pdf'                  -- ASYNC --                                                                        at Page. (C:\Users\lishun\AppData\Roaming\npm\node_modules\geek-t ime-topdf\node_modules\puppeteer\lib\helper.js:111:15)                               at printPage (C:\Users\lishun\AppData\Roaming\npm\node_modules\geek-time-top df\src\app.js:119:24)                                                                at pageToFile (C:\Users\lishun\AppData\Roaming\npm\node_modules\geek-time-to pdf\src\app.js:89:13)                                                                at async Object.downArticle (C:\Users\lishun\AppData\Roaming\npm\node_module s\geek-time-topdf\src\app.js:42:3)                                                   at async searchPrint (C:\Users\lishun\AppData\Roaming\npm\node_modules\geek- time-topdf\src\index.js:52:3)                                                        at async Command.start (C:\Users\lishun\AppData\Roaming\npm\node_modules\gee k-time-topdf\src\index.js:15:5) {                                                  errno: -4058,                                                                    code: 'ENOENT',                                                                  syscall: 'open',                                                                 path: 'D:\\js_code\\性能工程高手课\\0-开篇词 \| 代码不要眼前的苟且，而要效率的  提升和性能的优化.pdf'
--

**Comment by mydaoyuan** [comment]
@ls960972314 我这可以下载的，重新安装试试看
![image](https://user-images.githubusercontent.com/16152141/70995766-4938ba00-210c-11ea-918b-a139eec7af22.png)

**Comment by PichurChill** [comment]
window 下是因为， | 等字符是非法文件名，可以自己把项目拉下来，app.js 75行左右
```
  const fileFullName = `${fileName}.${fileType}`.replace(/\\|\/|:|\*|\?|"|<|>|\|/g, '')

```

**Comment by guowenfh** [comment]
@PichurChill 欢迎直接来个 PR

**Comment by guowenfh** [comment]
#25
