### ISSUE TITLE
初始化浏览器失败

### ISSUE THREAD

**Issue by MoeRookie** [guowenfh/geek-time-topdf#23]
始化浏览器失败 Error: Chromium revision is not downloaded.

**Comment by mydaoyuan** [comment]
重新安装一下 puppeteer 。 国内安装方法 [国内下载安装 Puppeteer 的方法](https://brickyang.github.io/2019/01/14/%E5%9B%BD%E5%86%85%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85-Puppeteer-%E7%9A%84%E6%96%B9%E6%B3%95/)
