### ISSUE TITLE
打印出错

### ISSUE THREAD

**Issue by xie0227** [guowenfh/geek-time-topdf#26]
打印出错 Error: ENOENT: no such file or directory, open 'E:\个人生活\数据结构与算法之美\0-开篇词 | 从今天起，跨过“数据结构与算法”这道坎.pdf'
  -- ASYNC --
    at Page.<anonymous> (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\node_modules\_puppeteer@1.20.0@puppeteer\lib\helper.js:111:15)
    at printPage (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:119:24)
    at pageToFile (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:89:13)
    at async Object.downArticle (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:42:3)
    at async searchPrint (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\index.js:52:3)
    at async Command.start (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\index.js:15:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\个人生活\\数据结构与算法之美\\0-开篇词 | 从今天起，跨过“数据结构与算法”这道坎.pdf'
}

**Comment by xie0227** [comment]
已经更改过.js里的文件名还是出错

**Comment by xie0227** [comment]
已经改过了.js的文件名问题

**Comment by xie0227** [comment]
打印出错 Error: ENOENT: no such file or directory, open

**Comment by guowenfh** [comment]
@xie0227 错误还是比较明显，文件夹或者文件路劲没有正常运行，看看是不是 windows 下路径拼接问题

**Comment by xie0227** [comment]
你好，我对这方面的知识不是很了解，所以可能得麻烦你能不能说明一下是什么文件夹或者文件路径没有正常运行。不是在git clone下来的那个项目的文件夹里进行gkpdf init吗。如果方便的话可以细说一下应该怎么纠正吗？现在又出现了超时的问题
打印出错 TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
&nbsp; &nbsp; at C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\node_modules\_puppeteer@1.20.0@puppeteer\lib\LifecycleWatcher.js:142:21
&nbsp; -- ASYNC --
&nbsp; &nbsp; at Frame.<anonymous&gt; (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\node_modules\_puppeteer@1.20.0@puppeteer\lib\helper.js:111:15)
&nbsp; &nbsp; at Page.goto (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\node_modules\_puppeteer@1.20.0@puppeteer\lib\Page.js:674:49)
&nbsp; &nbsp; at Page.<anonymous&gt; (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\node_modules\_puppeteer@1.20.0@puppeteer\lib\helper.js:112:23)
&nbsp; &nbsp; at setPageInfo (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:109:22)
&nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:97:5)
&nbsp; &nbsp; at async pageToFile (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:86:7)
&nbsp; &nbsp; at async Object.downArticle (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\app.js:42:3)
&nbsp; &nbsp; at async searchPrint (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\index.js:52:3)
&nbsp; &nbsp; at async Command.start (C:\Users\xie\AppData\Roaming\npm\node_modules\geek-time-topdf\src\index.js:15:5) {
&nbsp; name: 'TimeoutError'
}

非常感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"guowenfh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午1:20
收件人:&nbsp;"guowenfh/geek-time-topdf"<geek-time-topdf@noreply.github.com&gt;;
抄送:&nbsp;"coursera上的学生"<1105120355@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [guowenfh/geek-time-topdf] 打印出错 (#26)





 
@xie0227 错误还是比较明显，文件夹或者文件路劲没有正常运行，看看是不是 windows 下路径拼接问题
