### ISSUE TITLE
带有“选学”标签的篇章无法打印出内容，pdf里只有评论

### ISSUE THREAD

**Issue by diesang** [guowenfh/geek-time-topdf#27]
比如 白话法律42讲 里的：

一键直达 | 法律专栏“食用”指南
![image](https://user-images.githubusercontent.com/3785043/79036466-1191d880-7bfb-11ea-8382-545a6ca2b17c.png)

**Comment by yongrong** [comment]
和“选学”标签无关，有些正常章节也是有评论，无内容
