### ISSUE TITLE
无法在headless:true中登陆页面

### ISSUE THREAD

**Issue by HankBu** [guowenfh/geek-time-topdf#4]
无法在headless:true中登陆页面，page.content()被识别为<html><head></head><body></body></html>，应该是极客时间做了屏蔽，这里在考虑提个pr解决这个问题，谢谢！
如果在headless:false，可以正常跑，图片也可以下载，但想要的pdf格式不支持headless:false中，所以考虑其他方案。

**Comment by guowenfh** [comment]
这个问题确实是极客时间做了屏蔽，当在 headless:true 时， http请求时，直接被屏蔽了，HTTP code 451 HTTP 451 Unavailable For Legal Reasons / 因法律原因不可用，暂未有解决方案

**Comment by guowenfh** [comment]
@HankBu

**Comment by HankBu** [comment]
> 这个问题确实是极客时间做了屏蔽，当在 headless:true 时， http请求时，直接被屏蔽了，HTTP code 451 HTTP 451 Unavailable For Legal Reasons / 因法律原因不可用，暂未有解决方案

多谢，这里考虑使用接口+cookie方式下载，试验后也有屏蔽的问题，再考虑下其他方案。。。

**Comment by guowenfh** [comment]
@HankBu 3.0.0版本 已修复
