### ISSUE TITLE
无订阅课程

### ISSUE THREAD

**Issue by VictDog** [guowenfh/geek-time-topdf#8]
正在登录中，请耐心等候..
正在查找课程列表...
无已订阅课程
? 请选择你要打印的课程：
 (node:5151) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined

**Comment by VictDog** [comment]
确定不是网络原因

**Comment by Nil-Wang** [comment]
一样出现这个问题.

**Comment by guowenfh** [comment]
应该是再次进行安全升级了..

**Comment by guowenfh** [comment]
@VictDog @Nil-Wang 3.2.0 版 已修复
